#Automatization of creation of model indexes
spring.mongodb.auto-index-creation=true

# Logs of debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=DEBUG
