# creation of model indexes not automatic
spring.mongodb.auto-index-creation=false

# Only error logs
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR
logging.level.org.springframework.web=ERROR
