spring.application.name=evenMad

#Info API
server.port=8080
server.servlet.context-path=/api

# MongoDB string connection
spring.mongodb.uri=${MONGODB_URI}

#Transforms attribute name to snake_case
spring.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

# limitation and default set of pageable
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

# ignores mayus minus whene receiving an enum
spring.jackson.mapper.accept-case-insensitive-enums=true